// ── Scenario Templates ────────────────────────────────────────────────────────
// Pre-filled scenario skeletons that admins can use as a starting point.

import { AdminScenario, Difficulty, PressureLevel, MatchPhase, AttackOrDefence, DefensiveSystem } from './admin-storage';
import { HandballPosition } from './positions';

export interface ScenarioTemplate {
  id: string;
  name: string;
  description: string;
  icon: string;
  preset: Partial<AdminScenario>;
}

export const SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  {
    id: 'tpl-gk',
    name: 'Goalkeeper Scenario',
    description: 'A goalkeeper-focused shot-reading situation',
    icon: 'Shield',
    preset: {
      position: 'Goalkeeper',
      attackOrDefence: 'Defence',
      category: 'Backcourt Shots',
      difficulty: 'Intermediate',
      pressureLevel: 'Moderate',
      matchPhase: 'First Half',
      minute: 15,
      defensiveSystem: '6-0',
      situation: 'The right back receives the ball at 9m and prepares a jump shot. They have a clear lane and tend to shoot to the far corner.',
      question: 'What is your best positioning response?',
      answerOptions: [
        'Shift slightly to the far post, watch the release',
        'Hold centre and react to the ball',
        'Step out to narrow the angle',
        'Guess the far corner early',
      ],
      recommendedAnswer: 0,
      explanation: 'Shading the tendency while tracking the release gives you the best read.',
      learningObjective: 'Read the shooter\'s release point and anticipate shot direction.',
      mentalSkill: 'Reading the Shooter',
      tacticalSkill: 'Positioning',
      commonMistake: 'Guessing the shot direction before the release.',
      coachNote: 'Focus on patience — let the shooter show their hand first.',
    },
  },
  {
    id: 'tpl-cb',
    name: 'Centre Back Scenario',
    description: 'A playmaking decision against a defensive system',
    icon: 'Target',
    preset: {
      position: 'Centre Back',
      attackOrDefence: 'Attack',
      category: 'Reading 6:0 Defence',
      difficulty: 'Intermediate',
      pressureLevel: 'Moderate',
      matchPhase: 'First Half',
      minute: 18,
      defensiveSystem: '6-0',
      situation: 'The defence is set in a flat 6:0. Your back players are ready to cross. The wing is open on the left side.',
      question: 'What is the best attacking decision?',
      answerOptions: [
        'Cross with the left back, then pass to the wing',
        'Shoot from 9m immediately',
        'Pass directly to the pivot',
        'Hold the ball and wait for movement',
      ],
      recommendedAnswer: 0,
      explanation: 'A crossing action against a flat 6:0 creates gaps and opens the wing.',
      learningObjective: 'Recognise a flat 6:0 defence and exploit the gaps.',
      mentalSkill: 'Defence Reading',
      tacticalSkill: 'Crossing Action',
      commonMistake: 'Shooting immediately from 9m against a set flat defence.',
      coachNote: 'Encourage the crossing action before the final pass.',
    },
  },
  {
    id: 'tpl-back',
    name: 'Back Player Scenario',
    description: 'A backcourt shooting or passing decision',
    icon: 'Crosshair',
    preset: {
      position: 'Left Back',
      attackOrDefence: 'Attack',
      category: 'Long Range Decisions',
      difficulty: 'Advanced',
      pressureLevel: 'High',
      matchPhase: 'Second Half',
      minute: 42,
      defensiveSystem: '5-1',
      situation: 'You receive the ball at 9m. The defender is playing tight. The pivot is open on the right side and the wing is available on the left.',
      question: 'What is your best decision?',
      answerOptions: [
        'Drive left, draw the defender, pass to the pivot',
        'Shoot the jump shot from 9m',
        'Pass immediately to the wing',
        'Hold and reset the attack',
      ],
      recommendedAnswer: 0,
      explanation: 'Drawing the defender before passing to the pivot creates a high-percentage finish.',
      learningObjective: 'Choose between shooting, driving and passing based on the defender\'s stance.',
      mentalSkill: 'Decision Making',
      tacticalSkill: 'One Against One',
      commonMistake: 'Shooting from 9m when the defender is playing tight.',
      coachNote: 'Read the defender\'s stance before committing to the drive.',
    },
  },
  {
    id: 'tpl-wing',
    name: 'Wing Scenario',
    description: 'A wing finishing or fast break decision',
    icon: 'ArrowRight',
    preset: {
      position: 'Left Wing',
      attackOrDefence: 'Attack',
      category: 'Wing Finishing',
      difficulty: 'Intermediate',
      pressureLevel: 'Moderate',
      matchPhase: 'First Half',
      minute: 12,
      defensiveSystem: '6-0',
      situation: 'You receive the ball on the left wing with a narrow angle. The goalkeeper is positioned near the near post.',
      question: 'What is your best finishing option?',
      answerOptions: [
        'Shoot far post over the goalkeeper\'s reach',
        'Shoot near post low',
        'Lob the goalkeeper',
        'Pass back to the centre back',
      ],
      recommendedAnswer: 0,
      explanation: 'When the goalkeeper covers the near post, the far post is the highest-percentage finish.',
      learningObjective: 'Read the goalkeeper\'s positioning before choosing the finish.',
      mentalSkill: 'Goalkeeper Reading',
      tacticalSkill: 'Wing Finishing',
      commonMistake: 'Shooting near post when the goalkeeper is already there.',
      coachNote: 'Always check the goalkeeper\'s position before committing to the finish.',
    },
  },
  {
    id: 'tpl-pivot',
    name: 'Pivot Scenario',
    description: 'A pivot positioning or finishing decision',
    icon: 'Shield',
    preset: {
      position: 'Pivot',
      attackOrDefence: 'Attack',
      category: 'Finishing at Six Metres',
      difficulty: 'Advanced',
      pressureLevel: 'High',
      matchPhase: 'Second Half',
      minute: 35,
      defensiveSystem: '5-1',
      situation: 'You receive the ball at the 6m line with your back to goal. The defender is behind you. The goalkeeper is positioned centrally.',
      question: 'What is your best finishing option?',
      answerOptions: [
        'Spin and shoot low to the near post',
        'Spin and shoot high cross-court',
        'Pass back to the centre back',
        'Hold and wait for support',
      ],
      recommendedAnswer: 0,
      explanation: 'Pivots often shoot low on the spin — the near post is the highest-percentage finish.',
      learningObjective: 'Choose the highest-percentage finish from the pivot position.',
      mentalSkill: 'Composure',
      tacticalSkill: 'Finishing at Six Metres',
      commonMistake: 'Shooting high cross-court when the goalkeeper is centrally positioned.',
      coachNote: 'Practice the spin-and-shoot-low motion until it becomes automatic.',
    },
  },
  {
    id: 'tpl-pressure',
    name: 'Mental Pressure Scenario',
    description: 'A high-pressure mental decision scenario',
    icon: 'Clock',
    preset: {
      position: 'Goalkeeper',
      attackOrDefence: 'Defence',
      category: 'Pressure Situations',
      difficulty: 'Expert',
      pressureLevel: 'Critical',
      matchPhase: 'Second Half',
      minute: 59,
      defensiveSystem: '6-0',
      situation: '59:30 on the clock. Your team leads by one. The opposition needs a goal and sets up a 7 vs 6 attack, desperate to score.',
      question: 'What is your best response in this critical moment?',
      answerOptions: [
        'Hold position, communicate with defence',
        'Step out to intercept the extra player',
        'Stay on the line and react',
        'Rush the ball carrier',
      ],
      recommendedAnswer: 0,
      explanation: 'In the final minute, holding position and organising your defence is the safest path to preserving the lead.',
      learningObjective: 'Maintain composure and organise the defence in the final minute.',
      mentalSkill: 'Pressure Control',
      tacticalSkill: '7 vs 6 Defence',
      commonMistake: 'Rushing out of goal in the most critical moment.',
      coachNote: 'The final minute is about composure, not heroics.',
    },
  },
  {
    id: 'tpl-matchday',
    name: 'Match Day Scenario',
    description: 'A pre-match preparation scenario',
    icon: 'Calendar',
    preset: {
      position: 'Goalkeeper',
      attackOrDefence: 'Defence',
      category: 'Match Preparation',
      difficulty: 'Beginner',
      pressureLevel: 'Low',
      matchPhase: 'Warmup',
      minute: 0,
      defensiveSystem: '6-0',
      situation: 'You are in the warmup before a big match. The coach asks you to visualise the first three shots you might face.',
      question: 'What is the best mental preparation approach?',
      answerOptions: [
        'Visualise three different shot types and your responses',
        'Focus only on your strengths',
        'Think about the opponent\'s weaknesses',
        'Clear your mind completely',
      ],
      recommendedAnswer: 0,
      explanation: 'Visualising specific shot types and your responses prepares your mind for the decisions you will face.',
      learningObjective: 'Use visualisation as a pre-match mental preparation tool.',
      mentalSkill: 'Mental Preparation',
      tacticalSkill: 'Match Preparation',
      commonMistake: 'Not visualising specific scenarios before the match.',
      coachNote: 'Visualisation is a skill — practice it deliberately in every warmup.',
    },
  },
];

export function getTemplate(id: string): ScenarioTemplate | null {
  return SCENARIO_TEMPLATES.find((t) => t.id === id) ?? null;
}
